/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cb05;
import cb05.beans.EntradaSalidaBeans;
import cb05.control.EntradaSalidaControl;
import javax.swing.JOptionPane;

/**
 *
 * @author gem2u
 */
public class EntradaSalida extends javax.swing.JFrame {

    /**
     * Creates new form EntradaSalida
     */
    EntradaSalidaBeans esBeans = new EntradaSalidaBeans();
    EntradaSalidaControl esControl = new EntradaSalidaControl();
    
    public EntradaSalida() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloBN = new javax.swing.JLabel();
        lbB1 = new javax.swing.JLabel();
        cbB1 = new javax.swing.JComboBox<>();
        lbMensajeDigitos = new javax.swing.JLabel();
        lbResultadoDigitosPermitidos = new javax.swing.JLabel();
        lbMensajeNumero = new javax.swing.JLabel();
        tfEntradaNumero = new javax.swing.JTextField();
        lbMensajeResultado = new javax.swing.JLabel();
        lbB2 = new javax.swing.JLabel();
        cbB2 = new javax.swing.JComboBox<>();
        btContinuar = new javax.swing.JButton();
        btTerminar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        lbResultadoFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(442, 342));
        setMinimumSize(new java.awt.Dimension(442, 342));
        setResizable(false);

        lbTituloBN.setText("<html><center>ENTRE BASES NUMERICAS</center><br>B1 es la base fuente y B2 es la base destino</html>");

        lbB1.setText("Elija la Base 1");

        cbB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        cbB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbB1ActionPerformed(evt);
            }
        });

        lbMensajeDigitos.setText("Digitos Permitidos:");

        lbMensajeNumero.setText("Escriba el numero a convertir:");

        tfEntradaNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEntradaNumeroKeyReleased(evt);
            }
        });

        lbMensajeResultado.setText("Resultado:");

        lbB2.setText("Elija la Base 2");

        cbB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        cbB2.setSelectedIndex(1);
        cbB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbB2ActionPerformed(evt);
            }
        });

        btContinuar.setText("CONTINUAR");
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });

        btTerminar.setText("TERMINAR");
        btTerminar.setMaximumSize(new java.awt.Dimension(102, 31));
        btTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerminarActionPerformed(evt);
            }
        });

        btCancelar.setText("CANCELAR");
        btCancelar.setMaximumSize(new java.awt.Dimension(102, 31));
        btCancelar.setMinimumSize(new java.awt.Dimension(102, 31));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbB1)
                                .addGap(18, 18, 18)
                                .addComponent(cbB1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbMensajeDigitos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbResultadoDigitosPermitidos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMensajeResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbResultadoFinal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMensajeNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfEntradaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbB2)
                                .addGap(18, 18, 18)
                                .addComponent(cbB2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbTituloBN)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbTituloBN)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResultadoDigitosPermitidos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbB1)
                                .addComponent(cbB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbMensajeDigitos)))
                        .addGap(29, 29, 29)
                        .addComponent(lbMensajeNumero))
                    .addComponent(tfEntradaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbB2)
                    .addComponent(cbB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMensajeResultado)
                    .addComponent(lbResultadoFinal))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        // TODO add your handling code here:
        String numero = tfEntradaNumero.getText();
        esBeans.setEntradaNumero(numero);
        esControl.validacionCampos(esBeans.getB1(), esBeans.getB2(), esBeans.getEntradaNumero());
    }//GEN-LAST:event_btContinuarActionPerformed

    private void btTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerminarActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_btTerminarActionPerformed

    private void cbB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbB1ActionPerformed
        // TODO add your handling code here:
        String valorCB1 = (String) cbB1.getSelectedItem();
        int valorB1 = Integer.parseInt(valorCB1);
        esBeans.setB1(valorB1);
        if(valorB1 < 10){
            valorB1 -=1;
            lbResultadoDigitosPermitidos.setText("0 - "+valorB1);
        }
        else{
            switch(valorB1){
                case 11:{
                    lbResultadoDigitosPermitidos.setText("0-9 | A ");
                }break;
                case 12:{
                    lbResultadoDigitosPermitidos.setText("0-9 | A-B");
                }break;
                case 13:{
                    lbResultadoDigitosPermitidos.setText("0-9 | A-C");
                }break;
                case 14:{
                    lbResultadoDigitosPermitidos.setText("0-9 | A-D");
                }break;
                case 15:{
                    lbResultadoDigitosPermitidos.setText("0-9 | A-E");
                }break;
                case 16:{
                    lbResultadoDigitosPermitidos.setText("0-9 | A-F");
                }break;
            }
        }
    }//GEN-LAST:event_cbB1ActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cbB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbB2ActionPerformed
        // TODO add your handling code here:
        String valorCB2 = (String) cbB2.getSelectedItem();
        int valorB2 = Integer.parseInt(valorCB2);
        esBeans.setB2(valorB2);
    }//GEN-LAST:event_cbB2ActionPerformed

    private void tfEntradaNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEntradaNumeroKeyReleased
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        int b1 = esBeans.getB1();
        esControl.validacionNumero(validar, b1, evt);
    }//GEN-LAST:event_tfEntradaNumeroKeyReleased

    public void limpiarCampos(){
        cbB1.setSelectedIndex(0);//Reset al B1
        cbB2.setSelectedIndex(1);//Reset al B2
        lbResultadoDigitosPermitidos.setText("");//Borrar el resultado de los digitos permitidos
        tfEntradaNumero.setText("");//Borrar la entrada del numero
        lbResultadoFinal.setText("");//Borrar el resultado final
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaSalida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btContinuar;
    private javax.swing.JButton btTerminar;
    private javax.swing.JComboBox<String> cbB1;
    private javax.swing.JComboBox<String> cbB2;
    private javax.swing.JLabel lbB1;
    private javax.swing.JLabel lbB2;
    private javax.swing.JLabel lbMensajeDigitos;
    private javax.swing.JLabel lbMensajeNumero;
    private javax.swing.JLabel lbMensajeResultado;
    private javax.swing.JLabel lbResultadoDigitosPermitidos;
    private javax.swing.JLabel lbResultadoFinal;
    private javax.swing.JLabel lbTituloBN;
    private javax.swing.JTextField tfEntradaNumero;
    // End of variables declaration//GEN-END:variables
}
